import { CLASS_FRAMEWORK_ANNOTATIONS_FEATURE } from './analysis-features.js';
import {
  SPRING_AOP_FEATURE,
  SPRING_BEAN_INVENTORY_FEATURE,
  SPRING_CONDITIONALS_FEATURE,
  SPRING_NON_HTTP_HANDLERS_FEATURE,
  SPRING_ROUTE_BINDINGS_FEATURE,
} from './ingestion/frameworks/spring/analysis-features.js';
import {
  JAVA_ENUM_INTERFACE_HERITAGE_FEATURE,
  JAVA_RECORD_COMPONENT_ACCESSORS_FEATURE,
  SPRING_CONFIG_BINDINGS_FEATURE,
} from './ingestion/languages/java/analysis-features.js';

/** Production registry of independently versioned analysis capabilities. */
export const ANALYSIS_FEATURES = [
  CLASS_FRAMEWORK_ANNOTATIONS_FEATURE,
  SPRING_AOP_FEATURE,
  SPRING_BEAN_INVENTORY_FEATURE,
  SPRING_CONDITIONALS_FEATURE,
  SPRING_NON_HTTP_HANDLERS_FEATURE,
  SPRING_ROUTE_BINDINGS_FEATURE,
  SPRING_CONFIG_BINDINGS_FEATURE,
  JAVA_ENUM_INTERFACE_HERITAGE_FEATURE,
  JAVA_RECORD_COMPONENT_ACCESSORS_FEATURE,
] as const;
